<?php

$lang = array(
	'__app_hashtags'	=> "Hashtags",
	'menutab__hashtags_icon' => "hashtag",
	'menutab__hashtags' => "Hashtags",
	'menu__hashtags_overview' => "Overview",
	'menu__hashtags_overview_dashboard' => "Dashboard",
	'all_time_uniq_hashtags' => "All-Time Unique Hashtags",
	'all_time_most_used_hashtag' => "All-Time Most Used Hashtag</br>which has been used {# [1:time][?:times]}",
	'today_uniq_hashtags' => "Today's Unique Hashtags",
	'today_most_used_hashtag' => "Today's Most Used Hashtag</br>which has been used {# [1:time][?:times]}",
	'hashtags_general_statistics' => "General Statistics",
	'hashtags_usage_stats' => "Hashtags usage",
	'hashtags_stats_used_hashtags' => "Used hashtags across all apps",
	'hashtags_stats_used_app_hashtags' => "Used hashtags across ",
	'hashtags_trending' => "Trending hashtags",
	'hashtags_trending_none' => "No hashtags are trending at this moment.",
	'hashtags_trending_uses' => "Used {# [1:time][?:times]}",
	'hashtags_widget_title' => 'Widget title',
	'block_trendinghashtags' => 'Trending hashtags',
	'block_trendinghashtags_desc' => "Show trending hashtags across the board",
	'hashtags_trending_criteria_count' => "Number of occurences to be considered trending",
	'hashtags_trending_criteria_count_unlimited' => "Use most occurences criteria",
	'hashtags_trending_criteria_hours' => "Numbers of hours for trending criteria",
	'hashtags_trending_filter' => "Hashtags to filter out from trending",
	'hashtags_trending_filter_desc' => "Enter just the word without the #",
);
