<ips:template parameters="$hashtags, $title, $orientation='vertical'" />

<h3 class="ipsWidget_title ipsType_reset">
    {$title}
</h3>
<div class="ipsWidget_inner ipsPad_half">
    {{if empty($hashtags)}}
        <div class="ipsPad">
            <p class="ipsType_reset">
                {lang="hashtags_trending_none"}
            </p>
        </div>
    {{else}}
        {{if $orientation === 'vertical'}}
            <div class="ipsDataList">
                {{foreach $hashtags as $hashtag}}
                    <div class="ipsDataItem">
                        <div class="ipsDataItem_main">
                            <a href="{url='app=core&module=search&controller=search&hashtags='}{$hashtag['hashtag']}">
                                <strong class='ipsType_large' style="word-break: break-all;">#{$hashtag['hashtag']}</strong>
                            </a> <br />
                            <span class='ipsType_light'>
                                {lang="hashtags_trending_uses" pluralize="$hashtag['occurences']"}
                            </span>
                        </div>
                    </div>
                {{endforeach}}
            </div>
        {{else}}
            <div class="ipsCarousel ipsClearfix" data-ipscarousel>
                <div class="ipsCarousel_inner">
                    <div class="ipsList_reset" data-role="carouselItems">
                        {{foreach $hashtags as $hashtag}}
                            <div class="cHashtag_horizontal ipsCarousel_item">
                                <a href="{url='app=core&module=search&controller=search&hashtags='}{$hashtag['hashtag']}">
                                    <strong class='ipsType_large' style="word-break: break-all;">#{$hashtag['hashtag']}</strong>
                                </a> <br />
                                <span class='ipsType_light'>
                                    {lang="hashtags_trending_uses" pluralize="$hashtag['occurences']"}
                                </span>
                            </div>
                        {{endforeach}}
                    </div>
                    <span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
                    <span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
                    <a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
                    <a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
                </div>
            </div>
        {{endif}}
    {{endif}}
</div>